problemset: https://codeforces.ml/api/problemset.problems

username: moonandxinxin@qq.com
password: xinxin6635

groupId: 13376
title: helloWerds
announcement: miaomiao
beginTime: 2022-06-12 23:12:34
length: 5h12m
problems:
-   low: 800
    high: 1600
-   low: 1600
    high: 2000
-   low: 2000
    high: 2400